SERIAL_EXECUTABLE = "./serial"
PARALLEL_EXECUTABLE = "./parallel"
SERIAL_QUEUE_EXECUTABLE = "./serial_queue"

# number of times to repeat each experiment so we get representative data
CONSTANT_RERUN_COUNT = 1
UNIFORM_RERUN_COUNT = 1
# UNIFORM_RERUN_COUNT = 5
EXPONENTIAL_RERUN_COUNT = 1
# EXPONENTIAL_RERUN_COUNT = 12

CONSTANT = "C"
UNIFORM = "U"
EXPONENTIAL = "E"
